### ISSUE TITLE
Receipts unbenutzbar auf macOS Catalina 10.15.4 (speichert nicht mehr)

### ISSUE THREAD

**Issue by rinurinu** [holtwick/receipts#6]
Guten Tag
Receipts speichert nicht mehr auf macOS Catalina 10.15.4 (19E287), allerdings kommt auch keine Fehlermeldung. Wenn ich im Programm arbeite, sichere, das Programm oder auch nur die Datei schliesse und später wieder öffne, ist die Arbeit weg. Ein Blick auf die Datei erklärt auch wieso; Das Änderungsdatum der Datei ändert sich nicht, ich habe auch versucht die Datei zu kopieren und umzubenennen (da es leider kein «Speichern unter» gibt in Receipts), in der Hoffnung, dass dies das Problem vielleicht löst.
Für mein Unternehmen ist das verheerend, da ich darauf angewiesen bin, meine Buchhaltung regelmässig zu überprüfen. Was kann ich tun? Ich würde mich über eine Antwort freuen, ansonsten muss ich meine Daten in einem anderen Programm neu erfassen, was sehr schade wäre, denn ansonsten bin ich von Receipts richtig begeistert.
Liebe Grüsse
Rino

**Comment by holtwick** [comment]
Ich habe dir per Support geschrieben. Lass uns dort anhand der Log-Files versuchen das Problem einzugrenzen. Dank!
